# ********RoostGPT********

# Test generated by RoostGPT for test hsbc-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/accounts/{accountId}/transactions_get for http method type GET 
# RoostTestHash=6bae8a1897
# 
# 

# ********RoostGPT********
Feature: Account Transactions API

Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def token = karate.properties['AUTH_TOKEN']
    * def headers = { Authorization: '#(token)', 'x-fapi-auth-date': '2022-02-01T09:00:00Z', 'x-fapi-customer-ip-address': '192.168.1.1', 'x-fapi-interaction-id': '1', 'Accept-Language': 'en-US' }

Scenario Outline: Get Account Transactions
    Given path '/aisp/accounts/', '<accountId>', '/transactions'
    And params { fromDate: '<fromDate>', toDate: '<toDate>' }
    And headers headers
    When method get
    Then status 200
    And match response.data == '#object'
    And match response.data.transaction == '#array'
    And match response.data.transaction[0] == '#object'
    And match response.links == '#object'
    And match response.links.self == '#string'
    And match response.links.prev == '#string'
    And match response.links.next == '#string'

Examples:
    | accountId | fromDate     | toDate       |
    | '123456'  | '2022-01-01' | '2022-01-31' |
    | '789012'  | '2022-02-01' | '2022-02-28' |
