# ********RoostGPT********

# Test generated by RoostGPT for test hsbc-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/account-consents/{consentId}_get for http method type GET 
# RoostTestHash=705233235a
# 
# 

# ********RoostGPT********
Feature: Testing /aisp/account-consents/{consentId} endpoint

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Validate successful response for GET method
  Given path 'aisp/account-consents', '<consentId>'
  And header Authorization = karate.properties['AUTH_TOKEN']
  And header x-fapi-auth-date = '2022-01-01T00:00:00Z'
  And header x-fapi-customer-ip-address = '192.168.1.1'
  And header x-fapi-interaction-id = '12345678'
  And header Accept-Language = 'en-US,en;q=0.9'
  When method get
  Then status 200
  And match response.data.consentId == '<consentId>'
  And match response.data.creationDate == '#string'
  And match response.data.status == '#string'
  And match response.data.statusUpdateDate == '#string'
  And match response.data.permissions == '#array'
  And match response.data.expirationDate == '#string'
  And match response.data.transactionFromDate == '#string'
  And match response.data.transactionToDate == '#string'
  And match response.links.self == '#string'
  And match response.links.prev == '#string'
  And match response.links.next == '#string'
  And match response.headers['x-fapi-interaction-id'] == '#string'

Examples: 
  | consentId |
  | '1234' |
  | '5678' |
  | '9101' |
