# ********RoostGPT********

# Test generated by RoostGPT for test hsbc-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/account-consents_post for http method type POST 
# RoostTestHash=22b1c95aeb
# 
# 

# ********RoostGPT********
Feature: Test /aisp/account-consents API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def auth_token = karate.properties['AUTH_TOKEN']
  * def headers = {Authorization: '#(auth_token)', 'Content-Type': 'application/json'}

Scenario Outline: Test POST /aisp/account-consents
  Given path '/aisp/account-consents'
  And headers headers
  And request { 
    permissions: '<permissions>', 
    expirationDate: '2022-12-31T23:59:59Z', 
    transactionFromDate: '2021-01-01T00:00:00Z', 
    transactionToDate: '2022-12-31T23:59:59Z' 
  }
  When method post
  Then status <status>
  And match response == <response>
  And match response.headers == { 'Content-Type': 'application/json', 'x-fapi-interaction-id': '#string' }

Examples:
| permissions                                        | status | response   |
| ['ReadAccountsDetail', 'ReadBalances', 'ReadTransactionsDetail'] | 201     | {consentId:'#string', creationDate:'#string', status:'#string', statusUpdateDate:'#string', permissions:'#[]', expirationDate:'#string', transactionFromDate:'#string', transactionToDate:'#string'} |
| ['InvalidPermission']                              | 400     | {id:'#string', errors:'#[]'} |
