# ********RoostGPT********

# Test generated by RoostGPT for test hsbc-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/accounts_get for http method type GET 
# RoostTestHash=1174086886
# 
# 

# ********RoostGPT********
Feature: Validate /aisp/accounts endpoint

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Validate API response for <description>
  Given path '/aisp/accounts'
  And header Authorization = 'Bearer LbGDbcFVVfE-ngpjj8KaH5wrEfg'
  And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
  And header x-fapi-customer-ip-address = '169.254.169.254'
  And header x-fapi-interaction-id = '1234567890'
  And header Accept-Language = 'en-US'
  When method get
  Then status <statusCode>
  And match responseHeaders['Content-Type'] == ['application/json']
  # 'x-fapi-interaction-id' header not present in reponse so will fail' 
  And match responseHeaders['x-fapi-interaction-id'] == '1234567890' 
  And match response.data.account contains {accountId:'#string', accountNumber:'#string', accountType:'#string', accountSubType:'#string', productName:'#string', accountStatus:'#string', currency:'#string'}
  And match response.links contains {self:'#string'}

Examples:
  | description             | statusCode |
  | 'Successful Request'    | 200        |
#  | 'Bad Request'           | 400        |
#  | 'Unauthorised Request'  | 401        |
#  | 'Forbidden Request'     | 403        |
#  | 'Method Not Allowed'    | 405        |
#  | 'Not Acceptable'        | 406        |
#  | 'Too Many Requests'     | 429        |
#  | 'Internal Server Error' | 500        |
#  | 'Service Unavailable'   | 503        |
#  | 'Gateway Timeout'       | 504        |
# Examples for all other possible status codes cannot be tested as mock api is returning only status code 200 