# ********RoostGPT********

# Test generated by RoostGPT for test hsbc-karate using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /events_post for http method type POST 
# RoostTestHash=1ab63a6c31
# 
# 

# ********RoostGPT********
Feature: Events API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']
  * def headers = {Authorization: '#(authToken)', 'Content-Type': 'application/json', 'x-fapi-auth-date': 'test', 'x-fapi-customer-ip-address': 'test', 'x-fapi-interaction-id': 'test', 'Accept-Language': 'en-US'}

Scenario Outline: Validate POST /events API
  Given path '/events'
  And request """<requestBody>"""
  And headers headers
  When method post
  Then status <statusCode>
  And match response contains """<responseBody>"""

Examples:
|requestBody|statusCode|responseBody|
|{"ack":["test"],"returnImmediately":true,"maxEvents":1}|201|{"sets":{}, "moreAvailable":true}|
|{"ack":["test"],"returnImmediately":true,"maxEvents":1}|400|{"id":"", "errors":[]}|
|{"ack":["test"],"returnImmediately":true,"maxEvents":1}|401|{}|
|{"ack":["test"],"returnImmediately":true,"maxEvents":1}|403|{}|
|{"ack":["test"],"returnImmediately":true,"maxEvents":1}|405|{"id":"", "errors":[]}|
|{"ack":["test"],"returnImmediately":true,"maxEvents":1}|406|{"id":"", "errors":[]}|
|{"ack":["test"],"returnImmediately":true,"maxEvents":1}|415|{"id":"", "errors":[]}|
|{"ack":["test"],"returnImmediately":true,"maxEvents":1}|429|{"message":""}|
|{"ack":["test"],"returnImmediately":true,"maxEvents":1}|500|{"id":"", "errors":[]}|
|{"ack":["test"],"returnImmediately":true,"maxEvents":1}|503|{"message":""}|
|{"ack":["test"],"returnImmediately":true,"maxEvents":1}|504|{"message":""}|
