# ********RoostGPT********

# Test generated by RoostGPT for test OpenBanking-Postman using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /direct-debit-consents_post for http method type POST 
# RoostTestHash=4d53c1b804
# 
# 

# ********RoostGPT********
Feature: Testing /direct-debit-consents endpoint

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * configure headers = { Authorization: '#(authToken)', 'Content-Type': 'application/json', 'x-fapi-auth-date': 'Sun, 10 Sep 2017 19:43:31 UTC', 'x-fapi-customer-ip-address': '169.254.169.254', 'x-fapi-interaction-id': 'some-id', 'Accept-Language': 'en-US' }

  Scenario Outline: Test POST method with valid payload
    Given path '/direct-debit-consents'
    And request <payload>
    When method post
    Then status 201
    And match responseHeaders['x-fapi-interaction-id'] == '#string'
    And match response.data.consentId == '#string'
    And match response.data.statusUpdateDate == '#string'
    And match response.data.permissions == <permissions>

    Examples:
      | payload                                                                                                | permissions              |
      | { "data": { "permissions": ["string-1"], "expirationDate": "2017-04-05T10:43:07+00:00" } }             | ["string-1"]             |
      | { "data": { "permissions": ["string-2", "string-3"], "expirationDate": "2017-04-06T10:43:07+00:00" } } | ["string-2", "string-3"] |

  Scenario: Test POST method with invalid request payload
    Given path '/direct-debit-consents'
    And request {"data": {"permissions": [], "expirationDate": "2017-04-05T10:43:07+00:00"}}
    When method post
    Then status 400
    And match response.errors == '#[1..]'
    And match each response.errors contains { 'code': '#string' }
