# ********RoostGPT********

# Test generated by RoostGPT for test OpenBanking-Postman using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /direct-debit-consents/{consentId}_get for http method type GET 
# RoostTestHash=2b098d9178
# 
# 

# ********RoostGPT********
Feature: Real-time Direct Debit Consent Setup
  Background:
    Given def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    And url urlBase

  Scenario Outline: Get Consent Information
    Given path '/direct-debit-consents/', '<consentId>'
    And headers { Authorization: '<authToken>', 'x-fapi-auth-date': '<authDate>', 'x-fapi-customer-ip-address': '<customerIP>', 'x-fapi-interaction-id': '<interactionID>', 'Accept-Language': '<acceptLanguage>' }
    When method GET
    Then status 200
    And match responseHeaders == { 'x-fapi-interaction-id': '#string' }
    And match jsonResponse ==
      """
      {
        "data": {
          "consentId": "#string",
          "creationDate": "#string",
          "status": "#string",
          "statusUpdateDate": "#string",
          "permissions": '#[]'
        }
      }
      """

    Examples:
      | consentId | authToken                            | authDate                        | customerIP        | interactionID                          | acceptLanguage |
      | 123       | 'Bearer LbGDbcFVVfE-ngpjj8KaH5wrEfg' | 'Sun, 10 Sep 2017 19:43:31 UTC' | '169.254.169.254' | '7404e99b-1a4d-4b08-b441-c327661527f0' | 'en-US'        |
