# ********RoostGPT********

# Test generated by RoostGPT for test OpenBanking-Postman using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /direct-debit-consents/{consentId}_delete for http method type DELETE 
# RoostTestHash=f37b57ea61
# 
# 

# ********RoostGPT********
@consentDeletion
Feature: Consent Deletion Feature

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']

  Scenario Outline: Scenario for Real-time Direct Debit Consent Deletion
    Given path '/direct-debit-consents/', <consentId>
    And header Authorization = 'Bearer ' + AUTH_TOKEN
    And header x-fapi-auth-date = <date>
    And header x-fapi-customer-ip-address = <ip>
    And header x-fapi-interaction-id = <interaction_id>
    And header Accept-Language = <language>
    When method delete
    Then status <Status_Code>
    And match response contains {message: '#string'}

    Examples:
      | consentId                              | date                            | ip                | interaction_id | language | Status_Code |
      | '7404e99b-1a4d-4b08-b441-c327661527f0' | 'Sun, 10 Sep 2017 19:43:31 UTC' | '169.254.169.254' | 'abcdedfg1'    | 'en-US'  |         204 |
      | '7404e99b-1a4d-4b08-b441-c327661224rf' | 'Tue, 11 Sep 2018 18:43:32 UTC' | '169.254.169.152' | 'zzxxced500'   | 'en-GB'  |         204 |
