# ********RoostGPT********

# Test generated by RoostGPT for test OpenBanking-Postman using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /instructions_post for http method type POST 
# RoostTestHash=ca448ef838
# 
# 

# ********RoostGPT********
Feature: Testing /instructions endpoint

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Test POST method with different input payloads
    Given path '/instructions'
    And header Authorization = 'Bearer ' + authToken
    And header x-fapi-customer-ip-address = '<customerIp>'
    And header x-fapi-auth-date = '<authDate>'
    And header x-fapi-interaction-id = '<interactionId>'
    And header x-idempotency-key = '<idempotencyKey>'
    * def merchantInstructionIdentification = '<merchantInstructionIdentification>'
    * def creditorAccount = """<creditorAccount>"""
    * def instructedAmount = '<instructedAmount>'
    * def instructedAmountCurrency = '<instructedAmountCurrency>'
    And request "{ 'merchantInstructionIdentification': '#(merchantInstructionIdentification)', 'creditorAccount': '#(creditorAccount)', 'instructedAmount': '#(instructedAmount)', 'instructedAmountCurrency': '#(instructedAmountCurrency)' }"
    When method post
    Then status 201
    And match response == { paymentInformationStatus:'#string', processResult:'#object', transactionIdentification:'#string'  }

    Examples:
      | customerIp      | authDate                        | interactionId                          | idempotencyKey                         | merchantInstructionIdentification | creditorAccount                                                      | instructedAmount | instructedAmountCurrency |
      | '192.168.88.22' | 'Mon, 27 Sep 2021 19:43:31 GMT' | '3fa85f64-5717-4562-b3fc-2c963f66afa6' | 'e639e3dd-32cb-410a-8a5e-6b13c03ed842' | 'Invoice123'                      | '{ "bankCode":"123", "accountIdentification":"12345ABC", "currency":"SGD"}' | '100.00'         | 'SGD'                    |
