# ********RoostGPT********

# Test generated by RoostGPT for test OpenBanking-Postman using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /otpconfirmation_post for http method type POST 
# RoostTestHash=d300f02a96
# 
# 

# ********RoostGPT********
Feature: OTP Confirmation

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
    * def headers = { 
      'Authorization': 'Bearer ' + AUTH_TOKEN, 
      'x-fapi-customer-ip-address': '<ip_address>', 
      'x-fapi-auth-date': 'Sun, 10 Sep 2017 19:43:31 GMT', 
      'x-fapi-interaction-id': '<interaction_id>', 
      'x-idempotency-key': 'LbGpjj8KaH5wrEfg' 
      }

  Scenario Outline: Validation of OTP Confirmation
    Given path '/otpconfirmation'
    And headers headers
    And request """{
      "mandateIdentification": "<mandateIdentification>", 
      "otpIdentificationNumber": "<otpIdentificationNumber>",
      "otpPassword": "<otpPassword>",
      "creditorAccount": {
        "bankCode": "<bankCode>", 
        "accountIdentification": "<accountIdentification>",
        "currency":"<currency>", 
        "accountSchemeName": "<accountSchemeName>", 
        "accountSubType": "<accountSubType>"
      } 
    }"""
    When method post
    Then status 201
    And match response.processResult.responseCode == "<responseCode>"
    And match response.mandateIdentification == "<mandateIdentification>"
    And match response.creditorReference == "<creditorReference>"

    Examples:
    | mandateIdentification | otpIdentificationNumber | otpPassword | bankCode | accountIdentification | currency | accountSchemeName | accountSubType     | responseCode | creditorReference |
    | "ABC123"              | "XYZ789"                | "1234"      | "789"    | "12345678"             | "USD"   | "BBAN"            | "Current Account" | "201"        | "XYZ789"         |
