# ********RoostGPT********

# Test generated by RoostGPT for test OpenBanking-Postman using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /reports_post for http method type POST 
# RoostTestHash=81a4e7dbc4
# 
# 

# ********RoostGPT********
Feature: Fulfilment Endpoints

  Background: 
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: POST /reports
    Given path '/reports'
    And request { reportType: '<reportType>', reportingDate: '<reportingDate>', creditorAccount: { bankCode: '<bankCode>', accountIdentification: '<accountIdentification>', currency: '<currency>' } }
    And header Authorization = authToken
    And header x-idempotency-key = '<xIdempotencyKey>'
    When method post
    Then status 201

    Examples:
      | reportType | reportingDate | bankCode | accountIdentification | currency | xIdempotencyKey |
      | 'type1'    | '2021-01-01'  | '123'    | 'acc123'              | 'USD'    | 'key123'        |

  Scenario: POST /reports with missing fields
    Given path '/reports'
    And request { reportType: '', reportingDate: '', creditorAccount: { bankCode: '', accountIdentification: '', currency: '' } }
    And header Authorization = authToken
    And header x-idempotency-key = 'xIdempotencyKey'
    When method post
    Then status 400

  Scenario: POST /reports with incorrect authorization
    Given path '/reports'
    And request { reportType: 'reportType', reportingDate: 'reportingDate', creditorAccount: { bankCode: 'bankCode', accountIdentification: 'accountIdentification', currency: 'currency' } }
    And header Authorization = 'incorrectToken'
    And header x-idempotency-key = 'xIdempotencyKey'
    When method post
    Then status 401
