# ********RoostGPT********

# Test generated by RoostGPT for test OpenBanking-Postman using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /setup_post for http method type POST 
# RoostTestHash=7604674e87
# 
# 

# ********RoostGPT********
Feature: Test '/setup' RESTful API endpoints

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase

  Scenario Outline: Test POST '/setup' endpoint with different inputs
    Given path '/setup'
    And header Authorization = 'Bearer LbGDbcFVVfE-ngpjj8KaH5wrEfg'
    And header x-fapi-customer-ip-address = 'Customer IP Address'
    And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
    And header x-fapi-interaction-id = 'Interaction ID'
    And header x-idempotency-key = '<idempotency_key>'
    And request '''<request_body>'''
    When method POST
    Then status 201
    And match response.processResult.responseCode == '201'
    And match response.mandateIdentification == <string_place_holder>
    And match response.otpIdentificationNumber == <string_place_holder>
    And match response.mobileNumber == <string_place_holder>
    And match response.mandateStatus == <string_place_holder>

    Examples:
      | idempotency_key     | request_body                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | 'LbGpjj8KaH5wrEfg'  | """{ "merchantRequestIdentification": "MERCHANT_ID", "creditorReference": "CREDITOR_REF", "debtorName": "DEBTOR_NAME", "debtorAccount": "DEBTOR_ACC", "creditorName": "CREDITOR_NAME", "creditorAccount": "CREDITOR_ACC", "debtorPrivateIdentification": "PRIVATE_ID", "debtorPrivateIdentificationSchemeName": "SCHEME_NAME", "maximumAmountCurrency": "CURRENCY", "maximumAmount": "AMOUNT", "occurrences": "OCCURRENCES" }"""                          |
      | 'LsGpkl8TaH5wsEhg' | """{ "merchantRequestIdentification": "MERCHANT_ID_2", "creditorReference": "CREDITOR_REF_2", "debtorName": "DEBTOR_NAME_2", "debtorAccount": "DEBTOR_ACC_2", "creditorName": "CREDITOR_NAME_2", "creditorAccount": "CREDITOR_ACC_2", "debtorPrivateIdentification": "PRIVATE_ID_2", "debtorPrivateIdentificationSchemeName": "SCHEME_NAME_2", "maximumAmountCurrency": "CURRENCY_2", "maximumAmount": "AMOUNT_2", "occurrences": "OCCURRENCES_2" }"""|
