# ********RoostGPT********

# Test generated by RoostGPT for test OpenBanking-Postman using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /status/instructions_post for http method type POST 
# RoostTestHash=60872a3b7b
# 
# 

# ********RoostGPT********
Feature: Fulfilment endpoints

  Background:
    * def urlBase = karate.properties['url.base'] || 'http://localhost:8080'
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * def headers = { 'Authorization': '#('Bearer ' + authToken)', 'x-fapi-customer-ip-address': '192.168.1.1', 'x-fapi-auth-date': 'Sun, 10 Sep 2017 19:43:31 UTC', 'x-fapi-interaction-id': '84a55fa7-d5c7-4ae2-8c8c-9c50709a889f', 'x-idempotency-key': 'LbGpjj8KaH5wrEfg' }

  Scenario Outline: Get instruction status
    Given path '/status/instructions'
    And headers headers
    And request { 
                "merchantInstructionIdentification": "<merchantInstructionIdentification>", 
                "creditorAccount": { 
                                    "bankCode": "<bankCode>", 
                                    "accountIdentification": "<accountIdentification>", 
                                    "currency": "<currency>" 
                                    } 
                }
    When method post
    Then status <statusCode>
    And match response == <responseBody>

    Examples:
      | merchantInstructionIdentification | bankCode | accountIdentification | currency | statusCode | responseBody                                                                                                      |
      | 'ref123'                          | '001'    | 'A12345'              | 'USD'    |        201 | { paymentInformationStatus: 'ACSC', processResult: { responseCode: 'OK' }, transactionIdentification: '#string' } |
      | 'ref456'                          | '002'    | 'B67890'              | 'EUR'    |        400 | { id: '#string', errors: [ { code: 'OB.Field.Missing', causes: '#string' } ] }                                    |
      | 'ref789'                          | '003'    | 'C11223'              | 'GBP'    |        401 | { id: '#string', errors: [ { code: 'OB.Field.Expected', causes: '#string' } ] }                                   |
      | 'ref321'                          | '004'    | 'D44556'              | 'AUD'    |        403 | { id: '#string', errors: [ { code: 'OB.Field.Invalid', causes: '#string' } ] }                                    |
